spring:
  application:
    name: PhoenixBlog

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:********-q392emvaqfg15hr8behl3g98e407eqpa.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET:GOCSPX-2SA8OpOqeW5iw7ruBu********}
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:blog}
    username: ${DB_USER:super}
    password: ${DB_PASS:secret}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600_000
      max-lifetime: 1_800_000
      connection-timeout: 30_000

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none        # we use Flyway
      show-sql: false
      properties:
        hibernate:
          format_sql: true

    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true

jwt:
  secret: 854548452154854545