services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: super
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data: